spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/importe
      username: nkharin
      password: postgre
      driver-class-name: org.postgresql.Driver
    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    flyway:
        schemas: public
        baseline-on-migrate: true
        url: jdbc:postgresql://localhost:5432/importe
        user: "nkharin"
        password: "postgre"


